15:51:28,867 ADVERTÊNCIA [javax.enterprise.resource.webcontainer.jsf.lifecycle] (http-localhost-127.0.0.1-8080-2) #{contaController.transferenciaConta()}: javax.el.MethodNotFoundException: /caixa.xhtml @28,92 action="#{contaController.transferenciaConta()}": Method not found: br.com.brb.controller.ContaController@1971ea37.transferenciaConta(): javax.faces.FacesException: #{contaController.transferenciaConta()}: javax.el.MethodNotFoundException: /caixa.xhtml @28,92 action="#{contaController.transferenciaConta()}": Method not found: br.com.brb.controller.ContaController@1971ea37.transferenciaConta()
Caused by: javax.faces.el.MethodNotFoundException:
javax.el.MethodNotFoundException: /caixa.xhtml @28,92
action="#{contaController.transferenciaConta()}": Method not found:
br.com.brb.controller.ContaController@1971ea37.transferenciaConta()